package se.good_omens.EliteDangerous_TraderHelper.common.enums;

public enum COMMODITY_DATA {

	UNKNOWN(0, "Unknown", 0, COMMODITY_CATEGORY.UNKNOWN)

	, EXPLOSIVES(1, "Explosives", 263, COMMODITY_CATEGORY.CHEMICALS)
	, HYDROGEN_FUEL(2, "Hydrogen Fuel", 101, COMMODITY_CATEGORY.CHEMICALS)
	, MINERAL_OIL(3, "Mineral Oil", 181, COMMODITY_CATEGORY.CHEMICALS)
	, PESTICIDES(4, "Pesticides", 175, COMMODITY_CATEGORY.CHEMICALS)
	, CLOTHING(5, "Clothing", 299, COMMODITY_CATEGORY.CONSUMER_ITEMS)
	, CONSUMER_TECHNOLOGY(6, "Consumer Technology", 6901, COMMODITY_CATEGORY.CONSUMER_ITEMS)
	, DOMESTIC_APPLIANCES(7, "Domestic Appliances", 507, COMMODITY_CATEGORY.CONSUMER_ITEMS)
	, BEER(8, "Beer", 165, COMMODITY_CATEGORY.LEGAL_DRUGS)
	, LIQUOR(9, "Liquor", 628, COMMODITY_CATEGORY.LEGAL_DRUGS)
	, NARCOTICS(10, "Narcotics", 121, COMMODITY_CATEGORY.LEGAL_DRUGS)
	, TOBACCO(11, "Tobacco", 4831, COMMODITY_CATEGORY.LEGAL_DRUGS)
	, WINE(12, "Wine", 249, COMMODITY_CATEGORY.LEGAL_DRUGS)
	, ALGAE(13, "Algae", 112, COMMODITY_CATEGORY.FOODS)
	, ANIMAL_MEAT(14, "Animal Meat", 1308, COMMODITY_CATEGORY.FOODS)
	, COFFEE(15, "Coffee", 1284, COMMODITY_CATEGORY.FOODS)
	, FISH(16, "Fish", 404, COMMODITY_CATEGORY.FOODS)
	, FOOD_CARTRIDGES(17, "Food Cartridges", 87, COMMODITY_CATEGORY.FOODS)
	, FRUIT_AND_VEGETABLES(18, "Fruit and Vegetables", 296, COMMODITY_CATEGORY.FOODS)
	, GRAIN(19, "Grain", 190, COMMODITY_CATEGORY.FOODS)
	, SYNTHETIC_MEAT(20, "Synthetic Meat", 262, COMMODITY_CATEGORY.FOODS)
	, TEA(21, "Tea", 1481, COMMODITY_CATEGORY.FOODS)
	, POLYMERS(22, "Polymers", 117, COMMODITY_CATEGORY.INDUSTRIAL_MATERIALS)
	, SEMICONDUCTORS(23, "Semiconductors", 866, COMMODITY_CATEGORY.INDUSTRIAL_MATERIALS)
	, SUPERCONDUCTORS(24, "Superconductors", 6695, COMMODITY_CATEGORY.INDUSTRIAL_MATERIALS)
	, ATMOSPHERIC_PROCESSORS(25, "Atmospheric Processors", 324, COMMODITY_CATEGORY.MACHINERY)
	, CROP_HARVESTERS(26, "Crop Harvesters", 1990, COMMODITY_CATEGORY.MACHINERY)
	, MARINE_EQUIPMENT(27, "Marine Equipment", 3904, COMMODITY_CATEGORY.MACHINERY)
	, MICROBIAL_FURNACES(28, "Microbial Furnaces", 209, COMMODITY_CATEGORY.MACHINERY)
	, MINERAL_EXTRACTORS(29, "Mineral Extractors", 519, COMMODITY_CATEGORY.MACHINERY)
	, POWER_GENERATORS(30, "Power Generators", 472, COMMODITY_CATEGORY.MACHINERY)
	, WATER_PURIFIERS(31, "Water Purifiers", 253, COMMODITY_CATEGORY.MACHINERY)
	, AGRI_MEDICINES(32, "Agri-Medicines", 960, COMMODITY_CATEGORY.MEDICINES)
	, BASIC_MEDICINES(33, "Basic Medicines", 263, COMMODITY_CATEGORY.MEDICINES)
	, COMBAT_STABILISERS(34, "Combat Stabilisers", 2842, COMMODITY_CATEGORY.MEDICINES)
	, PERFORMANCE_ENHANCERS(35, "Performance Enhancers", 6935, COMMODITY_CATEGORY.MEDICINES)
	, PROGENITOR_CELLS(36, "Progenitor Cells", 6908, COMMODITY_CATEGORY.MEDICINES)
	, ALUMINIUM(37, "Aluminium", 289, COMMODITY_CATEGORY.METALS)
	, BERYLLIUM(38, "Beryllium", 8236, COMMODITY_CATEGORY.METALS)
	, COBALT(39, "Cobalt", 634, COMMODITY_CATEGORY.METALS)
	, COPPER(40, "Copper", 420, COMMODITY_CATEGORY.METALS)
	, GALLIUM(41, "Gallium", 5148, COMMODITY_CATEGORY.METALS)
	, GOLD(42, "Gold", 9442, COMMODITY_CATEGORY.METALS)
	, INDIUM(43, "Indium", 5836, COMMODITY_CATEGORY.METALS)
	, LITHIUM(44, "Lithium", 1547, COMMODITY_CATEGORY.METALS)
	, PALLADIUM(45, "Palladium", 13447, COMMODITY_CATEGORY.METALS)
	, PLATINUM(46, "Platinum", 19716, COMMODITY_CATEGORY.METALS)
	, SILVER(47, "Silver", 4776, COMMODITY_CATEGORY.METALS)
	, TANTALUM(48, "Tantalum", 3924, COMMODITY_CATEGORY.METALS)
	, TITANIUM(49, "Titanium", 946, COMMODITY_CATEGORY.METALS)
	, URANIUM(50, "Uranium", 2634, COMMODITY_CATEGORY.METALS)
	, BAUXITE(51, "Bauxite", 111, COMMODITY_CATEGORY.MINERALS)
	, BERTRANDITE(52, "Bertrandite", 2428, COMMODITY_CATEGORY.MINERALS)
	, COLTAN(53, "Coltan", 1353, COMMODITY_CATEGORY.MINERALS)
	, GALLITE(54, "Gallite", 1871, COMMODITY_CATEGORY.MINERALS)
	, INDITE(55, "Indite", 2140, COMMODITY_CATEGORY.MINERALS)
	, LEPIDOLITE(56, "Lepidolite", 555, COMMODITY_CATEGORY.MINERALS)
	, RUTILE(57, "Rutile", 294, COMMODITY_CATEGORY.MINERALS)
	, URANINITE(58, "Uraninite", 845, COMMODITY_CATEGORY.MINERALS)
	, IMPERIAL_SLAVES(59, "Imperial Slaves", 16058, COMMODITY_CATEGORY.SLAVERY)
	, SLAVES(60, "Slaves", 10256, COMMODITY_CATEGORY.SLAVERY)
	, ADVANCED_CATALYSERS(61, "Advanced Catalysers", 2901, COMMODITY_CATEGORY.TECHNOLOGY)
	, ANIMAL_MONITORS(62, "Animal Monitors", 267, COMMODITY_CATEGORY.TECHNOLOGY)
	, AQUAPONIC_SYSTEMS(63, "Aquaponic Systems", 252, COMMODITY_CATEGORY.TECHNOLOGY)
	, AUTO_FABRICATORS(64, "Auto-Fabricators", 3715, COMMODITY_CATEGORY.TECHNOLOGY)
	, BIOREDUCING_LICHEN(65, "Bioreducing Lichen", 981, COMMODITY_CATEGORY.TECHNOLOGY)
	, COMPUTER_COMPONENTS(66, "Computer Components", 414, COMMODITY_CATEGORY.TECHNOLOGY)
	, HE_SUITS(67, "H.E. Suits", 306, COMMODITY_CATEGORY.TECHNOLOGY)
	, LAND_ENRICHMENT_SYSTEMS(68, "Land Enrichment Systems", 4758, COMMODITY_CATEGORY.TECHNOLOGY)
	, RESONATING_SEPARATORS(69, "Resonating Separators", 6036, COMMODITY_CATEGORY.TECHNOLOGY)
	, ROBOTICS(70, "Robotics", 1802, COMMODITY_CATEGORY.TECHNOLOGY)
	, LEATHER(72, "Leather", 172, COMMODITY_CATEGORY.TEXTILES)
	, NATURAL_FABRICS(73, "Natural Fabrics", 412, COMMODITY_CATEGORY.TEXTILES)
	, SYNTHETIC_FABRICS(74, "Synthetic Fabrics", 154, COMMODITY_CATEGORY.TEXTILES)
	, BIOWASTE(75, "Biowaste", 20, COMMODITY_CATEGORY.WASTE)
	, CHEMICAL_WASTE(76, "Chemical Waste", 60, COMMODITY_CATEGORY.WASTE)
	, SCRAP(77, "Scrap", 44, COMMODITY_CATEGORY.WASTE)
	, NON_LETHAL_WEAPONS(78, "Non-lethal Weapons", 1821, COMMODITY_CATEGORY.WEAPONS)
	, PERSONAL_WEAPONS(79, "Personal Weapons", 4211, COMMODITY_CATEGORY.WEAPONS)
	, REACTIVE_ARMOUR(80, "Reactive Armour", 2095, COMMODITY_CATEGORY.WEAPONS)
	, BATTLE_WEAPONS(81, "Battle Weapons", 6474, COMMODITY_CATEGORY.WEAPONS)
	, TOXIC_WASTE(82, "Toxic Waste", 0, COMMODITY_CATEGORY.WASTE)
	, PAINITE(83, "Painite", 35972, COMMODITY_CATEGORY.MINERALS)
	, LIMPET(84, "Limpet", 0, COMMODITY_CATEGORY.UNKNOWN)
	, ERANIN_PEARL_WHISKEY(85, "Eranin Pearl Whiskey", 0, COMMODITY_CATEGORY.UNKNOWN)
	, KAMORIN_HISTORIC_WEAPONS(86, "Kamorin Historic Weapons", 2650, COMMODITY_CATEGORY.UNKNOWN)
	, LUCAN_ONION_HEAD(87, "Lucan Onion Head", 0, COMMODITY_CATEGORY.UNKNOWN)
	, MOTRONA_EXPERIENCE_JELLY(88, "Motrona Experience Jelly", 0, COMMODITY_CATEGORY.UNKNOWN)
	, ONION_HEAD(89, "Onion Head", 765, COMMODITY_CATEGORY.UNKNOWN)
	, RUSANI_OLD_SMOKEY(90, "Rusani Old Smokey", 0, COMMODITY_CATEGORY.UNKNOWN)
	, TARACH_SPICE(91, "Tarach Spice", 1056, COMMODITY_CATEGORY.UNKNOWN)
	, TERRA_MATER_BLOOD_BORES(92, "Terra Mater Blood Bores", 0, COMMODITY_CATEGORY.UNKNOWN)
	, WOLF_FESH(93, "Wolf Fesh", 712, COMMODITY_CATEGORY.UNKNOWN)
	, WUTHIELO_KU_FROTH(94, "Wuthielo Ku Froth", 420, COMMODITY_CATEGORY.UNKNOWN)
	, AI_RELICS(95, "Ai Relics", 144438, COMMODITY_CATEGORY.SALVAGE)
	, ANTIQUITIES(96, "Antiquities", 120365, COMMODITY_CATEGORY.SALVAGE)

	, NOT_DEFINED(666, "Not Defined", -1, COMMODITY_CATEGORY.NOT_DEFINED)
	;

	private int id;
	private String	name;
	private int	averagePrice;
	private COMMODITY_CATEGORY category;

	private COMMODITY_DATA(int id, String name, int averagePrice, COMMODITY_CATEGORY category) {
		this.id = id;
		this.name = name;
		this.averagePrice = averagePrice;
		this.category = category;
	}

	public int getAveragePrice() {
		return this.averagePrice;
	}

	public String getName() {
		return this.name;
	}

	public int getId() {
		return this.id;
	}

	public COMMODITY_CATEGORY getCategory() {
		return this.category;
	}

	public static COMMODITY_DATA fromString(String sought) {
		if((sought != null) || !sought.trim().isEmpty()) {
			for(COMMODITY_DATA item : COMMODITY_DATA.values()) {
				if(item.name().equalsIgnoreCase(sought)) {
					return item;
				}
			}
		}
		return COMMODITY_DATA.NOT_DEFINED;
	}

	public static COMMODITY_DATA fromInt(int id) {
		for(COMMODITY_DATA item : COMMODITY_DATA.values()) {
			if(item.getId() == id) {
				return item;
			}
		}
		return COMMODITY_DATA.NOT_DEFINED;
	}
}
